webapp/iotshm_dashboard/urls.py
from django.conf.urls import patterns, url
from iotshm_dashboard import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^change_password/complete/$', views.change_password_complete, name='change_password_complete'),
    url(r'^aboutiotshm/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contactus'),
    url(r'^contact/thanks/$', views.contact_thanks, name='contactus'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^dashboard/(?P<building_num>\d+)/real_time/$', views.real_time, name='real_time'),
    url(r'^dashboard/(?P<building_num>\d+)/$', views.building_info, name='building_info'),
    url(r'^dashboard/(?P<building_num>\d+)/long_term/$', views.long_term, name='long_term'),
    url(r'^dashboard/(?P<building_num>\d+)/sensors/$', views.sensors, name='sensors'),
    url(r'^dashboard/my_buildings/$', views.my_buildings, name='my_buildings'),
    url(r'^health/(?P<building_num>\d+)/$', views.health, name='health'),
    url(r'^real_time_ajax/(?P<building_num>\d+)/$', views.real_time_ajax, name='real_time_ajax'),
    url(r'^long_term_ajax/(?P<building_num>\d+)/$', views.long_term_ajax, name='long_term_ajax')
)

webapp/webapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^iotshm/', include('iotshm_dashboard.urls', namespace="iotshm_dashboard")),
    url(r'^admin/', include(admin.site.urls)),
)

webapp/templates/general/base.html
{% extends 'general/header_footer.html' %}
{% load bootstrap3 %}
{% bootstrap_javascript %}
{% bootstrap_css %}
<link href="{{ STATIC_URL }}style.css" rel="stylesheet" type="text/css"/>

{% block inside_headerfooter %}
    </br><hr />
     <div class="row" id="banner">
        <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 col-lg-offset-2 col-md-offset-2 col-sm-offset-2 col-xs-offset-2" align="left" style="margin-top: 40pt; margin-bottom: 40pt">
            {% block inside_base %}{% endblock %}
        </div>
    </div>
    <hr />
{% endblock %}

webapp/templates/general/header_footer.html
{% load bootstrap3 %}
{% bootstrap_javascript %}
{% bootstrap_css %}

<html>
    <link href="{{ STATIC_URL }}style.css" rel="stylesheet" type="text/css"/>
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>

    <body class="page-container" id="bgsplashcontainer">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 50px;
            }
        </style>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/iotshm/aboutiotshm/">IoT SHM</a>
                </div>
                <div class="navbar-collapse collapse" id="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a href="/iotshm/dashboard/">Home</a></li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Welcome, {{ user.first_name|capfirst }}<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/iotshm/logout/">Logout</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li><a href="/iotshm/">Home</a></li>
                            <li><a href="/iotshm/login/">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">{% block inside_headerfooter %}{% endblock %}</div>
    </body>
    <div align="center" class="navbar navbar-inverse navbar-fixed-bottom">
        </br><a align="left" href="/iotshm/contact/" style="color:white">Contact Us</a>
        <p style="display:inline; color:gray">   |   </p>
        <a align="right" href="/iotshm/aboutiotshm/" style="color:white">About IoT-SHM</a>
    </div>
</html>

webapp/templates/general/sidebar.html
{% extends 'general/header_footer.html' %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block inside_headerfooter %}
    <div class="col-lg-2 col-md-3 col-sm-3 sidebar-nav">
      <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="visible-xs navbar-brand">Navigate</span>
        </div>
        <div class="sidebar navbar-collapse collapse sidebar-navbar-collapse">
          <p></p>
          <div class="list-group">
              {% url 'iotshm_dashboard:dashboard' as dashboard %}
              {% url 'iotshm_dashboard:change_password' as change_password %}
              {% url 'iotshm_dashboard:my_buildings' as my_buildings %}
              <a {#Dashboard#}
                  class="list-group-item{% if request.path == dashboard %} active{% endif %}"
                  href="{{ dashboard }}">Dashboard
              </a>
{#              <a type="button" {#My Buildings - Details#}
{#                  class="list-group-item{% if request.path == my_buildings %} active{% endif %}"#}
{#                  href="{{ my_buildings }}">My Buildings#}
{#              </a>#}
              {% for building in buildings %}
                  {% url 'iotshm_dashboard:real_time' building.number as real_time %}
                  {% url 'iotshm_dashboard:building_info' building.number as building_info %}
                  {% url 'iotshm_dashboard:long_term' building.number as long_term %}
                  {% url 'iotshm_dashboard:sensors' building.number as sensors %}
                  <a
                      class="list-group-item{% if building == curr_building %} active{% endif %}"
                      {% if building == curr_building %}id = "active_building"{% endif %} value="{{ curr_building.number }}"
{#                      href="{{ building_info }}">Building #{{ building.number }}#}
                        href="{{ real_time }}">Building #{{ building.number }}
                      <span class="pull-right glyphicon glyphicon-chevron-{% if building == curr_building %}down{% else %}right{% endif %}"></span>
                  </a>
                  {% if request.path == real_time or request.path == long_term or request.path == building_info or request.path == sensors %}
                      {% if building == curr_building %}
                          <a style="font-size:12px"
                              class="list-group-item{% if request.path == real_time %} active{% endif %}"
                              href="{{ real_time }}">{% bootstrap_icon "play"   %}  Real Time Analysis
                          </a>
{#                          <a style="font-size:12px"#}
{#                              class="list-group-item{% if request.path == long_term %} active{% endif %}"#}
{#                              href="{{ long_term }}">{% bootstrap_icon "time" %}  Long Term Trends#}
{#                          </a>#}
                          <a style="font-size:12px"
                              class="list-group-item{% if request.path == sensors %} active{% endif %}"
                              href="{{ sensors }}">{% bootstrap_icon "info-sign" %}  Sensors
                          </a>
                      {% endif %}
                  {% endif %}
              {% endfor %}
              <a type="button"  href="" class="list-group-item disabled">Account</a>
              <a
                  class="list-group-item{% if request.path == change_password %} active{% endif %}"
                  href="{{ change_password }}">Change Password
              </a>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-10 col-md-9 col-sm-9" style="overflow:scroll;height:100%;background-color:rgba(255, 255, 255, 0.5)">
        {% block nextto_sidebar %}{% endblock %}
    </div>
{% endblock %}